# Required
version: 2

python:
  version: 3.6
  install:
    - requirements: docs/requirements.txt
  system_packages: true
  
build:
  image: latest

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
