name: csep-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy=1.18.4
  - pandas=0.25.1
  - scipy=1.3.1
  - matplotlib=3.1.1
  - seaborn=0.9.0
  - pyproj=1.9.6
  - obspy=1.2.1
  - python-dateutil=2.8.0
  - pytest=5.4.2
  - cartopy=0.17.0
  - vcrpy=4.0.2
  - gitpython=3.0.8
  - six=1.14.0
  - pytest-cov=2.8.1
  - basemap=1.2.1