name: csep
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy=1.17.0
  - pandas=0.24.2
  - scipy=1.2.1
  - matplotlib=3.1.1
  - seaborn=0.9.0
  - pyproj=1.9.6
  - obspy=1.1.0
  - python-dateutil=2.8.0
  - pytest=5.0.1
  - cartopy=0.17.0
  - vcrpy=2.0.1
  - gitpython=3.0.5