# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt-get install libproj-dev proj-data proj-bin  
        sudo apt-get install libgeos-dev 
        python -m pip install --upgrade pip
        pip install numpy==1.18.4
        pip install wheel
        pip install pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install PyCSEP
      run: |
        python setup.py install
    - name: Test with pytest
      run: |
        pytest --cov=./ --cov-config=.coveragerc
        bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
